#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AddressType {
    Airport,
    Business,
    CaravanPark,
    CommercialPark,
    CommunityDevelopment,
    EducationalInstitution,
    Entertainment,
    Hospital,
    Location,
    Marina,
    MilitaryBase,
    OverseasMilitary,
    Port,
    Primary,
    RecreationalPark,
    Resort,
    RetirementVillage,
    Rural,
    Secondary,
    ShoppingCentre,
    SportingCentre,
    Urban,
}
