[workspace]
members = [
    "crates/*"
]

resolver = "2"

[workspace.package]
version = "0.0.2-alpha.6"
authors = ["Benedikt Schwab <benedikt.schwab@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
categories = ["science::geo", "data-structures", "parser-implementations"]
keywords = ["gml", "geospatial", "3d", "geometry", "ogc"]
repository = "https://github.com/envis-space/egml"


[workspace.dependencies]
thiserror = "2.0.21"
anyhow = "1.0.104"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
nalgebra = "0.35.0"
parry3d-f64 = "0.31.1"
quick-xml = "0.42.0"
geo = "0.33.1"
itertools = "0.15.0"
rayon = "1.12.0"
approx = "0.5.1"
uuid = "1.27.0"
sha2 = "0.11.0"
earcut = "0.4.11"
strum = "0.28.0"
strum_macros = "0.28.0"
auto_enums = "0.8.10"
chrono = "0.4.45"
