use crate::util::XmlElement;
use strum::Display;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Display)]
pub enum GmlElement {
    BoundedByProperty,
    CompositeSurface,
    CurveMemberProperty,
    Envelope,
    ExteriorProperty,
    GeometryMemberProperty,
    GeometryMembersProperty,
    InteriorProperty,
    LineString,
    LinearRing,
    LowerCornerProperty,
    MultiCurve,
    MultiGeometry,
    MultiPoint,
    MultiSurface,
    NameProperty,
    PatchesProperty,
    Point,
    PointMemberProperty,
    PointMembersProperty,
    Polygon,
    PolygonPatch,
    Pos,
    PosListProperty,
    Ring,
    Shell,
    Solid,
    SolidMemberProperty,
    Surface,
    SurfaceMemberProperty,
    Triangle,
    TrianglePatchesProperty,
    TriangulatedSurface,
    UpperCornerProperty,
}

impl XmlElement for GmlElement {
    fn from_local_name(local_name: &str) -> Option<Self> {
        match local_name {
            "CompositeSurface" => Some(Self::CompositeSurface),
            "Envelope" => Some(Self::Envelope),
            "LineString" => Some(Self::LineString),
            "LinearRing" => Some(Self::LinearRing),
            "MultiCurve" => Some(Self::MultiCurve),
            "MultiGeometry" => Some(Self::MultiGeometry),
            "MultiPoint" => Some(Self::MultiPoint),
            "MultiSurface" => Some(Self::MultiSurface),
            "Point" => Some(Self::Point),
            "Polygon" => Some(Self::Polygon),
            "PolygonPatch" => Some(Self::PolygonPatch),
            "Ring" => Some(Self::Ring),
            "Shell" => Some(Self::Shell),
            "Solid" => Some(Self::Solid),
            "Surface" => Some(Self::Surface),
            "Triangle" => Some(Self::Triangle),
            "TriangulatedSurface" => Some(Self::TriangulatedSurface),
            "boundedBy" => Some(Self::BoundedByProperty),
            "curveMember" => Some(Self::CurveMemberProperty),
            "exterior" => Some(Self::ExteriorProperty),
            "geometryMember" => Some(Self::GeometryMemberProperty),
            "geometryMembers" => Some(Self::GeometryMembersProperty),
            "interior" => Some(Self::InteriorProperty),
            "lowerCorner" => Some(Self::LowerCornerProperty),
            "name" => Some(Self::NameProperty),
            "patches" => Some(Self::PatchesProperty),
            "pointMember" => Some(Self::PointMemberProperty),
            "pointMembers" => Some(Self::PointMembersProperty),
            "pos" => Some(Self::Pos),
            "posList" => Some(Self::PosListProperty),
            "solidMember" => Some(Self::SolidMemberProperty),
            "surfaceMember" => Some(Self::SurfaceMemberProperty),
            "trianglePatches" => Some(Self::TrianglePatchesProperty),
            "upperCorner" => Some(Self::UpperCornerProperty),
            _ => {
                tracing::debug!("unknown XML element: {local_name}");
                None
            }
        }
    }

    fn local_name(&self) -> &'static str {
        match self {
            GmlElement::BoundedByProperty => "boundedBy",
            GmlElement::CompositeSurface => "CompositeSurface",
            GmlElement::CurveMemberProperty => "curveMember",
            GmlElement::Envelope => "Envelope",
            GmlElement::ExteriorProperty => "exterior",
            GmlElement::GeometryMemberProperty => "geometryMember",
            GmlElement::GeometryMembersProperty => "geometryMembers",
            GmlElement::InteriorProperty => "interior",
            GmlElement::LineString => "LineString",
            GmlElement::LinearRing => "LinearRing",
            GmlElement::LowerCornerProperty => "lowerCorner",
            GmlElement::MultiCurve => "MultiCurve",
            GmlElement::MultiGeometry => "MultiGeometry",
            GmlElement::MultiPoint => "MultiPoint",
            GmlElement::MultiSurface => "MultiSurface",
            GmlElement::NameProperty => "name",
            GmlElement::PatchesProperty => "patches",
            GmlElement::Point => "Point",
            GmlElement::PointMemberProperty => "pointMember",
            GmlElement::PointMembersProperty => "pointMembers",
            GmlElement::Polygon => "Polygon",
            GmlElement::PolygonPatch => "PolygonPatch",
            GmlElement::Pos => "pos",
            GmlElement::PosListProperty => "posList",
            GmlElement::Ring => "Ring",
            GmlElement::Shell => "Shell",
            GmlElement::Solid => "Solid",
            GmlElement::SolidMemberProperty => "solidMember",
            GmlElement::Surface => "Surface",
            GmlElement::SurfaceMemberProperty => "surfaceMember",
            GmlElement::Triangle => "Triangle",
            GmlElement::TrianglePatchesProperty => "trianglePatches",
            GmlElement::TriangulatedSurface => "TriangulatedSurface",
            GmlElement::UpperCornerProperty => "upperCorner",
        }
    }
}
